name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and Release APK
  # You may pin to the exact commit or the version.
  # uses: sangatdesai/release-apk@4da4e6fe9db304b9c88dd0d3118496f89fda1f5a
      uses: sangatdesai/release-apk@V1.0